version: '3'
services:

  redis:
      image: redis:latest
      ports:
        - 6379:6379

  flowy_backend:
    build:
      context: ./flowy_backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis

  flowy_bot:
    build:
      context: ./flowy_bot
      dockerfile: Dockerfile
    depends_on:
      - flowy_backend

  celery_worker:
    build:
      context: ./flowy_backend
    depends_on:
      - flowy_backend
      - redis
    environment:
      - C_FORCE_ROOT=true
    command: celery -A flowy_backend worker
